#pragma once
#ifndef CAIRO_ELIXIR_NIF_ATOMS_H
#define CAIRO_ELIXIR_NIF_ATOMS_H

#define ATOMS \
  ATOM_DECL(ok,) \
  FORMAT_ATOMS \
  CONTENT_ATOMS \
  SURFACE_TYPE_ATOMS

#define FORMAT_ATOMS \
  ATOM_DECL(invalid, CAIRO_FORMAT_INVALID) \
  ATOM_DECL(argb32, CAIRO_FORMAT_ARGB32) \
  ATOM_DECL(rgb24, CAIRO_FORMAT_RGB24) \
  ATOM_DECL(a8, CAIRO_FORMAT_A8) \
  ATOM_DECL(a1, CAIRO_FORMAT_A1) \
  ATOM_DECL(rgb16_565, CAIRO_FORMAT_RGB16_565) \
  ATOM_DECL(rgb30, CAIRO_FORMAT_RGB30)

#define CONTENT_ATOMS \
  ATOM_DECL(color, CAIRO_CONTENT_COLOR) \
  ATOM_DECL(alpha, CAIRO_CONTENT_ALPHA) \
  ATOM_DECL(color_alpha, CAIRO_CONTENT_COLOR_ALPHA)

#define SURFACE_TYPE_ATOMS \
  ATOM_DECL(image, CAIRO_SURFACE_TYPE_IMAGE) \
  ATOM_DECL(pdf, CAIRO_SURFACE_TYPE_PDF) \
  ATOM_DECL(ps, CAIRO_SURFACE_TYPE_PS) \
  ATOM_DECL(xlib, CAIRO_SURFACE_TYPE_XLIB) \
  ATOM_DECL(xcb, CAIRO_SURFACE_TYPE_XCB) \
  ATOM_DECL(glitz, CAIRO_SURFACE_TYPE_GLITZ) \
  ATOM_DECL(quartz, CAIRO_SURFACE_TYPE_QUARTZ) \
  ATOM_DECL(win32, CAIRO_SURFACE_TYPE_WIN32) \
  ATOM_DECL(beos, CAIRO_SURFACE_TYPE_BEOS) \
  ATOM_DECL(directfb, CAIRO_SURFACE_TYPE_DIRECTFB) \
  ATOM_DECL(svg, CAIRO_SURFACE_TYPE_SVG) \
  ATOM_DECL(os2, CAIRO_SURFACE_TYPE_OS2) \
  ATOM_DECL(win32_printing, CAIRO_SURFACE_TYPE_WIN32_PRINTING) \
  ATOM_DECL(quartz_image, CAIRO_SURFACE_TYPE_QUARTZ_IMAGE) \
  ATOM_DECL(script, CAIRO_SURFACE_TYPE_SCRIPT) \
  ATOM_DECL(qt, CAIRO_SURFACE_TYPE_QT) \
  ATOM_DECL(recording, CAIRO_SURFACE_TYPE_RECORDING) \
  ATOM_DECL(vg, CAIRO_SURFACE_TYPE_VG) \
  ATOM_DECL(gl, CAIRO_SURFACE_TYPE_GL) \
  ATOM_DECL(drm, CAIRO_SURFACE_TYPE_DRM) \
  ATOM_DECL(tee, CAIRO_SURFACE_TYPE_TEE) \
  ATOM_DECL(xml, CAIRO_SURFACE_TYPE_XML) \
  ATOM_DECL(skia, CAIRO_SURFACE_TYPE_SKIA) \
  ATOM_DECL(subsurface, CAIRO_SURFACE_TYPE_SUBSURFACE) \
  ATOM_DECL(cogl, CAIRO_SURFACE_TYPE_COGL)

#endif
